### ISSUE TITLE
Empty login-name for github

### ISSUE THREAD

**Issue by Radon8472** [flydev-fr/BackendOAuth2#5]
I tried to implement a github login, but I always git empty-string as user and and empty array for emails.

I checked the your code and found the reason: 

in [___processLogin](https://github.com/flydev-fr/OAuth2Login/blob/0bd02ef93bbf0f888da070cf0f09f69db622d753/Oauth2Login.module#L131) you try to find data for a username, but in Github you must load the login-name via [$ownerDetails->getNickname()](https://github.com/thephpleague/oauth2-github/blob/266e9589a99e75bf696314e9ad8224009fccb91c/src/Provider/GithubResourceOwner.php#L70) fields like e.g. `name` are only optional profile extras you can not trust that they are filled.

So yust add one more line after the current "username"-Detection:

```php
if (empty($username) && method_exists($ownerDetails, 'getNickname')) {
  $username = $ownerDetails->getNickname() 
}
```

**Comment by flydev-fr** [comment]
Thanks @Radon8472 👍
